language: node_js
node_js: --lts
cache: npm
sudo: required
branches:
  only:
    - master

before_install:
  - npm install -g gatsby

install:
  - npm install

before_script:
  - git config user.name "zenghongtu"
  - git config user.email "zenghongtu@gmail.com"
  - sed -i'' "s~git@github.com:zenghongtu/zenghongtu.github.io.git~https://${GITHUB_TOKEN}@github.com/zenghongtu/zenghongtu.github.io.git~" package.json

script:
  - npm run deploy
